version: "3.9"

name: nchcsystem

networks:
  nchc:
    external: false
    
services:

  nchc_jupyter_ds:
    container_name: nchc_jupyter_ds  
    image: jupyter/datascience-notebook:latest
    ports:
      - 9999:9999
    volumes:    
      - ./storage:/storage    
      - ./storage/output:/output    
      - ./storage/jupyter_data:/workspace    
      - ./storage/hf_cache:/home/jovyan/.cache/huggingface      
    user: root
    environment:
      GRANT_SUDO: "yes"
      TZ: "Asia/Taipei"    
    restart: unless-stopped
    networks:
      - nchc 
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /workspace
    command: start-notebook.sh --NotebookApp.token=${SYSTEM_KEY} --notebook-dir=/workspace --port=9999
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]  
              
  nchc_qdrant:
    container_name: nchc_qdrant
    image: qdrant/qdrant:v1.8.4
    pull_policy: always    
    ports:
      - 6333:6333
      #- 6334:6334
    #expose:
    #  - 6333
    #  - 6334
    #  - 6335
    #configs:
    #  - source: qdrant_config
    #    target: /qdrant/config/production.yaml
    volumes:
      - ./storage/qdrant_data:/qdrant_data
      #- ./qdrant_storage:/qdrant/storage
      #- ./qdrant_config.yaml:/qdrant/config/production.yaml
    environment:
      - QDRANT__SERVICE__API_KEY=${SYSTEM_KEY}
    restart: always
    networks:
      - nchc 

  nchc_anythingllm:
    container_name: nchc_anythingllm
    image: mintplexlabs/anythingllm
    ports:
      - "3001:3001"
    volumes:
      - ./storage/anythingllm_data:/app/server/storage
      - ./storage/anythingllm_hotdir:/app/collector/hotdir
      - ./storage/anythingllm_outputs:/app/collector/outputs
      - ./anythingllm_env.txt:/app/server/.env
    environment:
      - STORAGE_DIR=/app/server/storage
    user: "${UID:-1000}:${GID:-1000}"
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    networks:
      - nchc
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
              
  nchc_ollama:
    container_name: nchc_ollama
    image: ollama/ollama:latest
    pull_policy: always
    ports:
      - 11434:11434    
    volumes:
      - ./storage/ollama_data:/root/.ollama
      - ./storage/output:/output          
    tty: true
    restart: unless-stopped
    networks:
      - nchc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
              
  nchc_openwebui:
    container_name: nchc_openwebui
    image: ghcr.io/open-webui/open-webui:main
    pull_policy: always
    ports:
      - 8080:8080
    volumes:
      - ./storage/openwebui_data:/app/backend/data
    restart: unless-stopped
    networks:
      - nchc
    depends_on:
      - nchc_ollama      
    environment:
      - '/ollama/api=http://nchc_ollama:11434/api'
      - 'OPENAI_API_BASE_URLS=${OPENAI_API_BASE_URLS}'
      - 'OPENAI_API_KEYS=${OPENAI_API_KEYS}'      
    extra_hosts:
      - host.docker.internal:host-gateway
     
  nchc_nginx:
    container_name: nchc_nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/biobank_ssl:/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - ./nginx/anythingllm.conf:/etc/nginx/conf.d/anythingllm.conf 
      - ./nginx/openwebui.conf:/etc/nginx/conf.d/openwebui.conf 
      - ./nginx/ollama.conf:/etc/nginx/conf.d/ollama.conf
      - ./nginx/qdrant.conf:/etc/nginx/conf.d/qdrant.conf
      - ./nginx/factory.conf:/etc/nginx/conf.d/factory.conf
      - ./nginx/llmbook.conf:/etc/nginx/conf.d/llmbook.conf
      - ./nginx/mergekit.conf:/etc/nginx/conf.d/mergekit.conf      
      - ./nginx/htpasswd.txt:/etc/nginx/.htpasswd  
      - ./website/assets:/usr/share/nginx/html/assets
      - ./website/index_ds_ip.html:/usr/share/nginx/html/index.html
    restart: always
    networks:
        - nchc
    depends_on:
      - nchc_openwebui         
    extra_hosts:
      - host.docker.internal:host-gateway
      

#configs:
#  qdrant_config:
#    content: |
#      log_level: INFO 